config/routes.rb
Rails.application.routes.draw do
  root to: 'pacientes#index'
  
  resources :pacientes
  resources :medicos
  resources :especialidades
  resources :convenios
end

app/models/especialidade.rb
class Especialidade < BaseResource
  self.site = "http://localhost:3000/api/v1"
end

app/controllers/especialidades_controller.rb
class EspecialidadesController < ApplicationController
  before_action :set_especialidade, only: [:show, :edit, :update, :destroy]

  # GET /especialidades
  # GET /especialidades.json
  def index
    @especialidades = Especialidade.all
  end

  # GET /especialidades/1
  # GET /especialidades/1.json
  def show
  end

  # GET /especialidades/new
  def new
    @especialidade = Especialidade.new
  end

  # GET /especialidades/1/edit
  def edit
  end

  # POST /especialidades
  # POST /especialidades.json
  def create
    @especialidade = Especialidade.new(especialidade_params)

    respond_to do |format|
      if @especialidade.save
        format.html { redirect_to @especialidade, notice: 'Especialidade was successfully created.' }
        format.json { render :show, status: :created, location: @especialidade }
      else
        format.html { render :new }
        format.json { render json: @especialidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especialidades/1
  # PATCH/PUT /especialidades/1.json
  def update
    respond_to do |format|
      if @especialidade.update_attributes(especialidade_params)
        format.html { redirect_to @especialidade, notice: 'Especialidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @especialidade }
      else
        format.html { render :edit }
        format.json { render json: @especialidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especialidades/1
  # DELETE /especialidades/1.json
  def destroy
  	respond_to do |format|
      if @especialidade.destroy
        format.html { redirect_to especialidades_url, notice: 'Especialidade was successfully destroyed.' }
        format.json { head :no_content }
      else
        #render :index, @especialidade.errors, status: :unprocessable_entity
        format.html { render :edit }
        format.json { render json: @especialidade.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especialidade
      @especialidade = Especialidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def especialidade_params
      params.require(:especialidade).permit(:nome)
    end
end

app/helpers/especialidades_helper.rb
module EspecialidadesHelper
end

app/views/especialidades/_form.html.erb
<%= form_with(model: especialidade, local: true) do |form| %>
  <% if especialidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(especialidade.errors.count, "error") %> prohibited this especialidade from being saved:</h2>

      <ul>
      <% especialidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :especialidade_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/especialidades/edit.html.erb
<h1>Editing Especialidade</h1>

<%= render 'form', especialidade: @especialidade %>

<%= link_to 'Show', @especialidade %> |
<%= link_to 'Back', especialidades_path %>

app/views/especialidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Especialidades</h1>
<hr>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @especialidades.each do |especialidade| %>
      <tr>
        <td><%= especialidade.nome %></td>
        <td><%= link_to 'Show', especialidade %></td>
        <td><%= link_to 'Edit', edit_especialidade_path(especialidade) %></td>
        <td><%= link_to 'Destroy', especialidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Especialidade', new_especialidade_path %>

app/views/especialidades/new.html.erb
<h1>New Especialidade</h1>

<%= render 'form', especialidade: @especialidade %>

<%= link_to 'Back', especialidades_path %>

app/views/especialidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @especialidade.nome %>
</p>

<%= link_to 'Edit', edit_especialidade_path(@especialidade) %> |
<%= link_to 'Back', especialidades_path %>