config/routes.rb
Rails.application.routes.draw do
  root to: 'pacientes#index'
  
  resources :pacientes
  resources :medicos
  resources :especialidades
  resources :convenios
end

app/models/paciente.rb
class Paciente < ActiveResource::Base
  self.site = "http://localhost:3000/api/v1"
  def convenio
  	@convenio ||= Convenio.find(self.convenio_id)
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)
    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update_attributes(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nome, :data_nascimento, :date, :rg, :telefone, :convenio_id)
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_with(model: paciente, local: true) do |form| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :paciente_nome %>
  </div>

  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.text_field :data_nascimento, id: :paciente_data_nascimento %>
  </div>

  <div class="field">
    <%= form.label :rg %>
    <%= form.text_field :rg, id: :paciente_rg %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :paciente_telefone %>
  </div>

  <div class="field">
    <%= form.label :convenio_id %>
    <%= form.collection_select(:convenio_id, Convenio.all, :id, :nome) %>
 

 
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<h1>Editing Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>
<hr>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data nascimento</th>
      
      <th>Rg</th>
      <th>Telefone</th>
      <th>Convenio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nome %></td>
        <td><%= paciente.data_nascimento %></td>
        <td><%= paciente.rg %></td>
        <td><%= paciente.telefone %></td>
        <td><%= paciente.convenio.nome %></td>
        
        <td><%= link_to 'Show', paciente %></td>
        <td><%= link_to 'Edit', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Destroy', paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paciente', new_paciente_path %>

app/views/pacientes/new.html.erb
<h1>New Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Back', pacientes_path %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @paciente.nome %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @paciente.data_nascimento %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @paciente.rg %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @paciente.telefone %>
</p>

<p>
  <strong>Convenio:</strong>
  <%= @paciente.convenio.nome %>
</p>

<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>