config/routes.rb
Rails.application.routes.draw do
  root to: 'pacientes#index'
  
  resources :pacientes
  resources :medicos
  resources :especialidades
  resources :convenios
end

app/models/convenio.rb
class Convenio < BaseResource
  self.site = "http://localhost:3000/api/v1"
end

app/controllers/convenios_controller.rb
class ConveniosController < ApplicationController
  before_action :set_convenio, only: [:show, :edit, :update, :destroy]

  # GET /convenios
  # GET /convenios.json
  def index
    @convenios = Convenio.all
  end

  # GET /convenios/1
  # GET /convenios/1.json
  def show
  end

  # GET /convenios/new
  def new
    @convenio = Convenio.new
  end

  # GET /convenios/1/edit
  def edit
  end

  # POST /convenios
  # POST /convenios.json
  def create
    @convenio = Convenio.new(convenio_params)

    respond_to do |format|
      if @convenio.save
        format.html { redirect_to @convenio, notice: 'Convenio was successfully created.' }
        format.json { render :show, status: :created, location: @convenio }
      else
        format.html { render :new }
        format.json { render json: @convenio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /convenios/1
  # PATCH/PUT /convenios/1.json
  def update
    respond_to do |format|
      if @convenio.update_attributes(convenio_params)
        format.html { redirect_to @convenio, notice: 'Convenio was successfully updated.' }
        format.json { render :show, status: :ok, location: @convenio }
      else
        format.html { render :edit }
        format.json { render json: @convenio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /convenios/1
  # DELETE /convenios/1.json
  

   def destroy
    respond_to do |format|
      if @convenio.destroy
        format.html { redirect_to convenio_url, notice: 'Convenio was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @onvenio.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_convenio
      @convenio = Convenio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def convenio_params
      params.require(:convenio).permit(:nome)
    end
end

app/helpers/convenios_helper.rb
module ConveniosHelper
end

app/views/convenios/_form.html.erb
<%= form_with(model: convenio, local: true) do |form| %>
  <% if convenio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(convenio.errors.count, "error") %> prohibited this convenio from being saved:</h2>

      <ul>
      <% convenio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :convenio_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/convenios/edit.html.erb
<h1>Editing Convenio</h1>

<%= render 'form', convenio: @convenio %>

<%= link_to 'Show', @convenio %> |
<%= link_to 'Back', convenios_path %>

app/views/convenios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Convenios</h1>
<hr>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @convenios.each do |convenio| %>
      <tr>
        <td><%= convenio.nome %></td>
        <td><%= link_to 'Show', convenio %></td>
        <td><%= link_to 'Edit', edit_convenio_path(convenio) %></td>
        <td><%= link_to 'Destroy', convenio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Convenio', new_convenio_path %>

app/views/convenios/new.html.erb
<h1>New Convenio</h1>

<%= render 'form', convenio: @convenio %>

<%= link_to 'Back', convenios_path %>

app/views/convenios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @convenio.nome %>
</p>

<%= link_to 'Edit', edit_convenio_path(@convenio) %> |
<%= link_to 'Back', convenios_path %>