config/routes.rb
Rails.application.routes.draw do
  root to: 'pacientes#index'
  
  resources :pacientes
  resources :medicos
  resources :especialidades
  resources :convenios
end

app/models/medico.rb
class Medico < ActiveResource::Base
  self.site = "http://localhost:3000/api/v1"

  def especialidade
  	@especialidade ||= Especialidade.find(self.especialidade_id)
  end
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy]

  # GET /medicos
  # GET /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)
    respond_to do |format|
      if @medico.save
        format.html { redirect_to @medico, notice: 'Medico was successfully created.' }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update_attributes(medico_params)
        format.html { redirect_to @medico, notice: 'Medico was successfully updated.' }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url, notice: 'Medico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:nome, :especialidade_id)
    end
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/views/medicos/_form.html.erb
<%= form_with(model: medico, local: true) do |form| %>
  <% if medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% medico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :medico_nome %>
  </div>

  <div class="field">
    <%= form.label :especialidade_id %>
    <%#= form.text_field :especialidade_id, id: :medico_especialidade_id %>
    <%= form.collection_select(:especialidade_id, Especialidade.all, :id, :nome) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medicos/edit.html.erb
<h1>Editing Medico</h1>

<%= render 'form', medico: @medico %>

<%= link_to 'Show', @medico %> |
<%= link_to 'Back', medicos_path %>

app/views/medicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medicos</h1>
<hr>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Especialidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= medico.nome %></td>
        <td><%= medico.especialidade.nome %></td>
        <td><%= link_to 'Show', medico %></td>
        <td><%= link_to 'Edit', edit_medico_path(medico) %></td>
        <td><%= link_to 'Destroy', medico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medico', new_medico_path %>

app/views/medicos/new.html.erb
<h1>New Medico</h1>

<%= render 'form', medico: @medico %>

<%= link_to 'Back', medicos_path %>

app/views/medicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @medico.nome %>
</p>

<p>
  <strong>Especialidade:</strong>
  <%= @medico.especialidade.nome %>
</p>

<%= link_to 'Edit', edit_medico_path(@medico) %> |
<%= link_to 'Back', medicos_path %>